#!/usr/bin/env python3
"""
Build self-contained, single-file HTML exports from the source pages.

Why a script and not hand-copied files: the moment there are two copies of a
page, they drift, and the copy that goes to a designer is the one that gets
looked at. Re-run this after any edit to a page or to styles.css.

What it does, and nothing more:
  - inlines styles.css into a <style> block, replacing the <link rel=stylesheet>
  - drops <script> tags (the pages render fully without JS; the only script is
    the reveal-on-scroll progressive enhancement)
  - neutralises .reveal so content is visible with no JS to un-hide it
  - rewrites internal page links to '#' so a designer opening the file from
    disk does not hit a wall of 404s
  - inlines every assets/ image as a base64 data URI, in both src="" and the
    stylesheet's url() references, so the single file really is single
  - leaves font <link>s pointing at Google Fonts, which is what a designer needs

Outputs: emr-inc-standalone.html, emr-inc-research-standalone.html
"""

import base64
import mimetypes
import pathlib
import re

HERE = pathlib.Path(__file__).parent
CSS = (HERE / "styles.css").read_text()


def data_uri(rel_path):
    p = HERE / rel_path
    assert p.is_file(), f"referenced asset missing on disk: {rel_path}"
    mime, _ = mimetypes.guess_type(p.name)
    assert mime, f"cannot type asset: {rel_path}"
    return f"data:{mime};base64,{base64.b64encode(p.read_bytes()).decode()}"


def inline_assets(text):
    """Replace src="assets/..." and url("assets/...") with data URIs."""
    def sub_src(m):
        return f'{m.group(1)}="{data_uri(m.group(2))}"'

    def sub_url(m):
        return f'url("{data_uri(m.group(1))}")'

    text, n_src = re.subn(r'(src)="(assets/[^"]+)"', sub_src, text)
    text, n_url = re.subn(r'url\("(assets/[^"]+)"\)', sub_url, text)
    return text, n_src + n_url

# source page -> (output name, strings that MUST survive the build)
# The guards are the point of this table. A silent content loss during a
# regex rewrite is the failure mode worth catching, so every page names the
# figures it is not allowed to lose.
PAGES = {
    "index.html": (
        "emr-inc-standalone.html",
        ["The civil service has a data problem.", "56.20%", "82,503"],
    ),
    "research.html": (
        "emr-inc-research-standalone.html",
        ["23.34%", "23.26%", "172,564", "47,087", "2,291", "56.20%", "35,416"],
    ),
}


def build(src_name, out_name, must_survive):
    html = (HERE / src_name).read_text()

    # --- 1. inline the stylesheet --------------------------------------------
    link_re = re.compile(r'[ \t]*<link[^>]+href="styles\.css"[^>]*>\n?')
    assert link_re.search(html), f"{src_name}: stylesheet link not found"
    html = link_re.sub(
        "  <style>\n" + CSS + "\n"
        "  /* Standalone build: no JavaScript ships with this file, so the\n"
        "     reveal-on-scroll enhancement must not be allowed to hide anything. */\n"
        "  .reveal { opacity: 1 !important; transform: none !important; }\n"
        "  </style>\n",
        html,
        count=1,
    )

    # --- 2. strip scripts ----------------------------------------------------
    # The head script only sets a `.js` class. Every hidden-then-revealed rule
    # is scoped to that class, so removing the script leaves the page fully
    # rendered. Its explanatory comment goes with it, or it reads as a lie.
    html = re.sub(r"[ \t]*<!-- Set before first paint\.[\s\S]*?-->\n?", "", html, count=1)
    html, n_scripts = re.subn(
        r"[ \t]*<script\b[\s\S]*?</script>\n?", "", html, flags=re.IGNORECASE
    )

    # --- 3. dead internal links -> '#' ---------------------------------------
    # Only .html targets. Leaves #anchors, mailto: and absolute URLs alone.
    html, n_links = re.subn(
        r'href="(?!https?:|mailto:|#)[^"]*\.html(#[^"]*)?"', 'href="#"', html
    )

    # --- 3b. inline images ----------------------------------------------------
    # After step 1 the cork url() lives inside the <style> block, so one pass
    # over the whole document covers both markup and stylesheet references.
    html, n_assets = inline_assets(html)

    # --- 4. label it so nobody mistakes it for the source --------------------
    html = html.replace(
        "<head>",
        "<head>\n"
        f"  <!-- STANDALONE BUILD. Generated by build-standalone.py from\n"
        f"       {src_name} + styles.css. Do not edit this file; edit the\n"
        f"       sources and re-run. -->",
        1,
    )

    # Assert on live references only. The word "styles.css" is allowed to
    # appear in a comment; an href or src pointing at it is not, because that
    # is what would make the file non-portable.
    assert not re.search(r'(href|src)="[^"]*styles\.css', html), f"{out_name}: live css ref"
    assert "<script" not in html.lower(), f"{out_name}: a script survived"
    assert 'src="assets/' not in html and 'url("assets/' not in html, \
        f"{out_name}: a relative asset reference survived"
    for needle in must_survive:
        assert needle in html, f"{out_name}: LOST {needle!r}"

    (HERE / out_name).write_text(html)
    print(f"wrote {out_name}  ({len(html):,} bytes)  "
          f"scripts removed: {n_scripts}  links neutralised: {n_links}  "
          f"assets inlined: {n_assets}")


for src, (out, guards) in PAGES.items():
    build(src, out, guards)
